name: Update Telegram feed

on:
  workflow_dispatch:
  schedule:
    # Every 6 hours
    - cron: "17 */6 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "scripts/requirements.txt"

      - name: Install dependencies
        run: python -m pip install -r scripts/requirements.txt

      - name: Generate feed.json
        env:
          # Optional: add OPENAI_API_KEY (and optionally OPENAI_MODEL) as repo secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
        run: python scripts/update_telegram_feed.py --channel chillhousetech --limit 25 --out feed.json --translator auto

      - name: Commit and push (if changed)
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add feed.json
          git commit -m "Update Telegram feed"
          git push


